### ISSUE TITLE
Maven central and 1.1.4+

### ISSUE THREAD

**Issue by gluser1357** [blackears/svgSalamander#111]
Hi community, it is correct that releases can be found on maven central, e. g. https://mvnrepository.com/artifact/com.github.blackears/svgSalamander/v1.1.3? If so, would it be possible to upload the most current 1.1.4 there in order to access it via normal maven coords? Thank you :)

**Comment by devemux86** [comment]
@blackears I tried the GitHub artifact (with a Gradle project), but it does not work.

It returns "Unauthorized".
Does it expect users to have a GitHub username/password? This shouldn't happen.
```
Could not GET 'https://maven.pkg.github.com/blackears/svgSalamander/com/github/blackears/svg-salamander/1.1.5/svg-salamander-1.1.5.pom'. Received status code 401 from server: Unauthorized
```

**Comment by devemux86** [comment]
@blackears Thanks!

If you check JitPack, you'll see that it fails to build release `1.1.5`:
https://jitpack.io/#blackears/svgSalamander

The log is here: https://jitpack.io/com/github/blackears/svgSalamander/v1.1.5/build.log
`[ERROR] Failed to execute goal on project svg-salamander-examples: Could not resolve dependencies for project com.github.blackears:svg-salamander-examples:jar:1.1.5: Could not find artifact com.github.blackears:svgSalamander:jar:1.1.5 in central (https://repo.maven.apache.org/maven2)`

Why does the example module search the library module on Maven?
All modules should use the library module with local references.

Can you build the project locally?
If you can build the project locally, then JitPack can also build it successfully.

**Comment by devemux86** [comment]
@blackears 

In [Mapsforge](https://github.com/mapsforge/mapsforge) and [VTM](https://github.com/mapsforge/vtm) I use Gradle that has much simpler declarations.

To publish on JitPack, all I had to do was add the `jitpack.yml` file and everything worked automatically.

**Comment by blackears** [comment]
SVG Salamander requires running a language compiler as a build step, so it's not as straight forward as most builds.  Again, something that was really easy to do under Ant, but much harder to do with Maven.  I'm also trying to remember things I did more than 5 years ago now.

**Comment by devemux86** [comment]
Maven recently changed the publishing process again.

That's why many projects stopped publishing to Maven and now prefer JitPack:
- https://github.com/mapsforge/mapsforge/pull/1711
- https://github.com/mapsforge/vtm/pull/1234
- https://github.com/AppDevNext/AndroidChart/pull/383

**Comment by blackears** [comment]
I just need a simple and straight forward set of instructions for publishing this.  Like I said, I haven't touched Java in about 10 years now, save for bug fixes to this project.  None of these websites have concise descriptions of what you need to do to publish something.  That's all I care about at this point.

**Comment by gluser1357** [comment]
> I just need a simple and straight forward set of instructions for publishing this.

Ok, I'll try:
   
>  - Missing signature for file: svgSalamander-1.1.5-sources.jar
>  - Missing signature for file: svgSalamander-1.1.5-javadoc.jar
>  - Missing signature for file: svgSalamander-1.1.5.jar
>  - Missing signature for file: svgSalamander-1.1.5.pom

In svg-core/pom.xml I see a version "3.4.2" for maven-gpg-plugin (master branch). This version doesn't seem to exist (org.apache.maven.plugins:maven-gpg-plugin:jar:3.4.2 was not found). For me it works with "3.2.8" which is currently the latest version. I guess the error could then disappear.

> - Namespace 'com.github.blackears' is not allowed

This error occured when trying to publish to Sonatype, right? Now, by a bit of googleing I found two ways how your artifact could be published:

**Publish to Maven Central Repository** (IMO the preferred way)

Up from July 2025, to submitted an artifact to the Central Repository (https://repo1.maven.org/maven2/), these artifact must be submitted to https://central.sonatype.com (which are later be sync'ed to the Central Repository). As I can see, no **com.github.blackears** namespace (groupId) is available on central.sonatype.com which is causing the "namespace not allowed" error above. It further seems that **com.github.*** namespaces cannot be registered anymore since 2021. The preferred way for projects on github seems to be **io.github.***, thus **io.github.blackears**.

I'd suggest to try the following steps (UNTESTED):

- create a https://central.sonatype.com and register "via Github"
- claim and verify namespace io.github.blackears
- generate a user token via Account setttings to create _token-username_ and _token-password_
- store both properties in your settings.xml on the system where you build the project (id "central" must correspond to publishingServerId "central" in your svg-core/pom.xml):

```
<server>
    <id>central</id>
    <username>[token-username]</username> 
    <password>[token-password]</password> 
</server>
```

- in your project's README you write "_Starting with version 1.1.5, the artifact name is now svg-salamander instead of svgSalamander. This is due to the package hosting switching to Github from Sonotype, and my not being able to reuse the old artifact name on Github._". I don't see the reason to not reuse "svgSalamander", but, IMO "svg-salamander" is more common for maven artifacts so I'd go with this syntax.
- I'd suggest to adapt your pom.xml's in master-branch:
  - change the groupIds from com.github.blackears to io.github.blackears (reason see above)
  - change the artifactIds from svgSalamander[Xxx] to "svg-salamander[-xxx]"
  - change the versions from 1.1.5 e. g. to 1.1.5.1-SNAPSHOT for testing (IMO versions in master should always end on -SNAPSHOT)
- (*) build your project, e. g. via mvn clean verify, and check if pgp plugin ran
- commit changes to Github
- create a tag in Github, e. g. by mvn release, to create 1.1.5.1
- deploy your project artifact to sonatype do a mvn clean deploy -Pdeploy from 1.1.5.1 (as part of your Github action?)
- if successful, log in to the Sonatype Central Portal to validate and release (Publish) the uploaded bundle. The artifact should then be synchronized to repo1.maven.org/maven2.
- try to add 1.1.5.1 as dependency in a maven test project (without adding additional repositories like https://maven.pkg.github.com/blackears/svgSalamander!) and verify that the artifact will be really loaded from Maven Central (e. g. by removing the artifact in your .m2 before building your test project) and is usable.
- when everything works, set versions in all pom.xml's to 1.1.6-SNAPSHOT and repeat up from (*) to publish the real productive 1.1.6 artifact to Maven central
- afterwards,
  - check if pom.xml's versions are 1.1.7-SNAPSHOT
  - in README
    - change groupId to "io.github.blackears"
    - verify artifactId "svg-salamander"
    - change version to "1.1.6"
    - remove the (unnecessary) "repositories" section
    - correct "Salamader" in Documents section ;-)
  -  remove the (unnecessary) jitpack.yml

**Publishing to JitPack repo** (as alternative to Maven Central Repository)

- would require to additionally add a second repository for all projects using svg-salamander since, in contrast to Sonatype Repo, it is not sync'ed to Maven Central Repo
- the error "_Could not resolve dependencies for project com.github.blackears:svg-salamander-examples:jar:1.1.5: Could not find artifact com.github.blackears:svgSalamander:jar:1.1.5 in central (https://repo.maven.apache.org/maven2)_" above could be due to the fact that not all versions were equal to 1.1.5 when building, where maven tried to load the (non-local) missing dependency from a external repository (?)
- after correcting the version of maven-gpg-plugin (see above) and using jitpack.yml this should could as well (not tested).

HTH

**Comment by blackears** [comment]
I tried following your suggestions.  Still can't deploy.  Running `mvn clean deploy -Pdeploy` in the terminal prints a lot of errors related to javadoc and fails.  Trying to deploy from within Eclipse also fails.

Not sure what I'm doing wrong.  Is the problem just javadoc?  I tried to disable javadoc errors but it seems not to work.

I also feel like I'm back in the infernal depths of Maven hell trying to figure out why this horrible system refuses to work.

**Comment by devemux86** [comment]
@blackears Version `1.1.5.1` fails to build on [JitPack](https://jitpack.io/#blackears/svgSalamander) with an error of Examples again:

https://jitpack.io/com/github/blackears/svgSalamander/v1.1.5.1/build.log

`[ERROR] Failed to execute goal on project svg-salamander-examples: Could not resolve dependencies for project io.github.blackears:svg-salamander-examples:jar:1.1.5.1-SNAPSHOT: Could not find artifact io.github.blackears:svgSalamander:jar:1.1.5.1-SNAPSHOT`

As we only need the lib module to be published, maybe exclude the Examples from the release?

**Comment by gluser1357** [comment]
@blackears: Thank you for testing. I checked again - two more fixes are required:
 
- in **svg-example/pom.xml** please change "svgSalamander" to "svg-salamander" in the dependencies section to fix the svg-examples build. This is required due to the renaming of the artifacts from svgSalamander to svg-salamander.
- in **/svg-core/src/main/java/com/kitfox/svg/xml/cpx/CPXOutputStream.java** please change "tt" to "code" in all opening and closing **tt** tags in the method comments to resolve the javadoc errors _Tag not supported in HTML5: tt"_.

`mvn clean deploy -Pdeploy` should work then. At least, if I run the following commands locally I get only expected warnings but no errors anymore:
- `mvn clean install`:
  - no errors 
- `mvn clean deploy`:
  - _Using credentials from server id central in settings.xml ... Unable to get publisher server properties for server id: central_
  - this is correct since I dont have the sonatype central credentials in settings.xml
- `mvn clean deploy -Pdeploy`:
  - _Could not determine gpg version_
  - This is also correct since I dont have gpg installed

Could you please fix and try once more (for 1.1.5.2 and finally 1.1.6?)

@devemux86:
- If deployment to Maven central (that @blackears obviously prefer) will be successful, publishing to Jitpack will not be necessary in my eyes (so jitpack.yml should be removed from the project to avoid confusion).
- just for interest, what steps have to be done exactly to deploy to Jitpack: Creating a tag and do a release via Github UI, and in which ordering?
- if Jitpack is still of interest the _[ERROR] Failed to execute goal on project svg-salamander-examples: Could not resolve dependencies for project io.github.blackears:svg-salamander-examples:jar:1.1.5.1-SNAPSHOT_ should also be gone by fixing the both points I mentioned.

**Comment by devemux86** [comment]
> just for interest, what steps have to be done exactly to deploy to Jitpack: Creating a tag and do a release via Github UI, and in which ordering?

@gluser1357 

I publish [Mapsforge](https://github.com/mapsforge/mapsforge) and [VTM](https://github.com/mapsforge/vtm) map libraries in JitPack automatically with 2 simple steps:
- Include a `jitpack.yml` file in the repository

- Tag and release in GitHub so JitPack reads it automatically

**Comment by blackears** [comment]
Okay, I didn't realize I needed to publish it on Sonatype too.  I've done that and I hope it is public shortly.

How do I find out the proper dependency info is for the README?

**Comment by blackears** [comment]
Okay, I published 1.1.5.2.  Thanks for your help with this.  This is the hardest to use and most complex deployment system I've ever worked with.

I created the three projects so that I could separate the testing code from the main project.  But I don't really understand how to design the pom system, and it's probably not set up correctly.  Only the svg-salamander module is required.

Is there a naming convention for git tags verses releases?  I think you said earlier I should have a tag for non-SNAPSHOT, but am not sure what to name it.

**Comment by devemux86** [comment]
> I published 1.1.5.2

@blackears Can you also create a GitHub release for new versions?

https://github.com/blackears/svgSalamander/releases

**Comment by devemux86** [comment]
JitPack build still does not work for version `1.1.5.2`:
https://jitpack.io/com/github/blackears/svgSalamander/v1.1.5.2/build.log

`Failed to execute goal on project svg-salamander-examples: Could not resolve dependencies for project io.github.blackears:svg-salamander-examples:jar:1.1.5.2-SNAPSHOT: Could not find artifact io.github.blackears:svg-salamander:jar:1.1.5.2-SNAPSHOT`

Probably the example module should be excluded from the publish on repositories.
